# url of influxdb to store monitoring data
influxdb_url: https://192.168.222.171:30086

# database name of influxdb
influxdb_name: telegraf

telegraf_global_tags: []

telegraf_agent_package_method: offline
telegraf_agent_package_local_dir: "/root"
